import http from '@/services/HttpService'
import Head from 'next/head'
import Link from 'next/link';

export default function Home({ coins }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col items-center'>
        {coins.items.map(coin => (
          <Link key={coin.id} className='py-4' href={'/coins/' + (coin.id).toLowerCase() + '-' + (coin.name).toLowerCase().replace(/\s/g, '-')}>
            {coin.name}
          </Link>
        ))}
      </main>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const { data } = await http.get('/coins')
  return {
    props: {
      coins: data
    }
  }
}
